### ISSUE TITLE
autogen error

### ISSUE THREAD

**Issue by crypto512** [recitale/recitale#16]
I'm trying to use autogen but it fails with the following error.
```
# find .
./D1
./D1/1.jpg
./D1/settings.yaml
./D1/2.jpg
./D2
./D2/3.jpg
./D2/4.jpg
./D2/settings.yaml
./settings.yaml

# cat settings.yaml
title: "Title"
sub_title: "Subtitle"

# cat D1/settings.yaml

title: D1
date: 2023-02-01
cover: 1.jpg

# cat D2/settings.yaml
title: D2
date: 2004-07-01
cover: 3.jpg

# recitale --log-level=DEBUG autogen --all
Traceback (most recent call last):
  File "/usr/local/bin/recitale", line 33, in <module>
    sys.exit(load_entry_point('recitale==2.0.0a5', 'console_scripts', 'recitale')())
  File "/usr/local/lib/python3.10/dist-packages/recitale-2.0.0a5-py3.10.egg/recitale/recitale.py", line 871, in main
    autogen(args.folder, args.force)
  File "/usr/local/lib/python3.10/dist-packages/recitale-2.0.0a5-py3.10.egg/recitale/autogen.py", line 93, in autogen
    build_template(folder, force)
  File "/usr/local/lib/python3.10/dist-packages/recitale-2.0.0a5-py3.10.egg/recitale/autogen.py", line 72, in build_template
    files_grabbed.extend(glob(Path(".").joinpath(folder, files)))
  File "/usr/lib/python3.10/glob.py", line 24, in glob
    return list(iglob(pathname, root_dir=root_dir, dir_fd=dir_fd, recursive=recursive))
  File "/usr/lib/python3.10/glob.py", line 42, in iglob
    root_dir = pathname[:0]
TypeError: 'PosixPath' object is not subscriptable
```

**Comment by QSchulz** [comment]
Thanks for the report! Could you please try #17 ?

Once you check out the correct branch in the git repository, you can run the local recitale with
```
PYTHONPATH=/path/to/recitale python3 -m recitale.recitale autogen --log-level DEBUG --all
```

**Comment by crypto512** [comment]
Thanks for your fix it works with my basic test and a real gallery. Very happy that you work on the project again.

May I suggest 3 things to improve autogen:
- having to set the cover image before generating is time consuming for large directory structure, choosing the first image by default will be a great speedup for me.
- putting the date of the cover image will also be a good start!
- and last for the name :D it should default to directory if not provided.
