### ISSUE TITLE
unable to override pictures-group.html

### ISSUE THREAD

**Issue by NaanProphet** [recitale/recitale#44]
Hello first of all thank you for this fork!

I'm trying to customize the generation of picture groups. I downloaded the original HTML file from the repo and put in `templates/sections/picture-group.html`.

Before modifying anything, I tried running a build and it blows up trying to find my image file.

```
2023-09-16 02:04:01,541 WARNING (recitale.py:189) - warning: If you want the rss, OpenGraph and/or the social network share to work, you need to specify the website url in root settings
Building galleries:  50%|█████     | 1/2 | ETA: 00:00
Traceback (most recent call last):
  File "/usr/local/bin/recitale", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/recitale/recitale.py", line 897, in main
    process_directory(
  File "/usr/local/lib/python3.11/site-packages/recitale/recitale.py", line 296, in process_directory
    build_gallery(settings, gallery_settings, gallery_path, parent_templates)
  File "/usr/local/lib/python3.11/site-packages/recitale/recitale.py", line 431, in build_gallery
    __build_gallery(
  File "/usr/local/lib/python3.11/site-packages/recitale/recitale.py", line 393, in __build_gallery
    html = template_to_render.render(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.11/site-packages/recitale/themes/light/templates/gallery-index.html", line 32, in top-level template code
    {% include "sections/" + section.type + ".html" %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/templates/sections/pictures-group.html", line 30, in top-level template code
    <a href="{{ image.copy() }}" {% if caption %}data-caption="{{ caption }}"{% endif %}
^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/recitale/image.py", line 62, in copy
    width, height = imagesize.get(self.filepath)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/imagesize/imagesize.py", line 96, in get
    fhandle = open(filepath, 'rb')
              ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'gallery_1/light/IMG_1927.jpg'
```

It seems somehow that the theme `light` is being added to the file path somehow? Any help most appreciated, thanks!

**Comment by NaanProphet** [comment]
Interesting, I tried it again now it is building but all the img `src` attributes are blank.

I think it is because of line 36 of the HTML ... why is `src` empty?

`<img class="lazy responsive-img z-depth-2" src="" data-original="{{ image.thumbnail((None, 600)) }}" alt="">`
